In [6]:
revenues = [120, 250, 80, 310, 95]
tax_rate = 0.18
discount_rate = 0.10

 Part 1. 
   #  1.1 revenues including tax

In [13]:
import pandas as pd
revenues =  [120, 250, 80, 310, 95]
    
df= pd.DataFrame({"revenue": revenues})
t = 0.18
df['revenue_including_tax'] = df["revenue"] * (1+t)
print(df)

   revenue  revenue_including_tax
0      120                  141.6
1      250                  295.0
2       80                   94.4
3      310                  365.8
4       95                  112.1

# 1.2 final revenues after tax and discount

In [19]:
import pandas as pd
revenues =  [120, 250, 80, 310, 95]
        
df= pd.DataFrame({"r": revenues})
df['final_revenue'] = df["r"] * (1+0.18) * (1-0.10)
print(df)

     r  final_revenue
0  120         127.44
1  250         265.50
2   80          84.96
3  310         329.22
4   95         100.89

# 1.3. Boolean list indicating whether revenue > 100.

In [ ]:
df["high_revenue"] = df["final_revenue"] > 100
print(df)

     r  final_revenue  is_high_revenue  high_revenue
0  120         127.44             True          True
1  250         265.50             True          True
2   80          84.96            False         False
3  310         329.22             True          True
4   95         100.89             True          True

In [37]:
df["final_revenue"] > 100

0     True
1     True
2    False
3     True
4     True
Name: final_revenue, dtype: bool

# 1.4. Boolean list indicating whether revenue is between 100 and 300.

In [33]:
df["mid_revenue"] = (df["final_revenue"] >= 100) & (df["final_revenue"] <= 300)
print(df)

     r  final_revenue  is_high_revenue  high_revenue  mid_revenue
0  120         127.44             True          True         True
1  250         265.50             True          True         True
2   80          84.96            False         False        False
3  310         329.22             True          True        False
4   95         100.89             True          True         True

Part 2
 # 2.1 Compute total revenue manually using a loop

In [62]:
sales = [120, 250, 80, 310, 95]

total = 0
for value in sales:
    total += value
total

855

# 2.2 Compute average revenue.

In [67]:
sales = [120, 250, 80, 310, 95]
average = sum(sales)/len(sales)
average

171.0

# 2.3 Identify the maximum value without using max().

In [55]:
sales = [120, 250, 80, 310, 95]
maximum = sales[0]
for value in sales:
    if value > maximum:
        maximum = value
maximum

310

# 2.5 Create a new list of revenues after adding 5% commission.

In [59]:
sales = [120, 250, 80, 310, 95]
new_sales = []

for value in sales:
    new_sales.append(value + value * 0.05)

print(new_sales)

[126.0, 262.5, 84.0, 325.5, 99.75]

Part 4
# 4.1 Remove duplicates using a set.

In [18]:
customer_ids = [1, 2, 3, 3, 4, 5, 5, 6]
unique_set = set(customer_ids)
unique_set

{1, 2, 3, 4, 5, 6}

# 4.2 Convert back to a list.

In [19]:
my_list = list(unique_set)
print(my_list)

[1, 2, 3, 4, 5, 6]

# 4.3 Compare lengths before and after deduplication.

In [21]:
print(len(customer_ids))
print(len(my_set))

8
6

Part 5
# 5.1 Add a new key "segment" based on revenue.

In [24]:
customer = {
    "name": "Anna",
    "revenue": 250,
    "city": "Yerevan"
}
customer["segment"] = "Premium"
customer

{'name': 'Anna', 'revenue': 250, 'city': 'Yerevan', 'segment': 'Premium'}

# 5.2 Update revenue to 300.

In [25]:
customer["revenue"] = 300
customer

{'name': 'Anna', 'revenue': 300, 'city': 'Yerevan', 'segment': 'Premium'}

# 5.3 Remove "city".

In [26]:
del customer["city"]
customer

{'name': 'Anna', 'revenue': 300, 'segment': 'Premium'}

# 5.4 Loop over the dictionary and print key-value pairs.

In [38]:
for key,value in customer.items():
    print(key,value)

name Anna
revenue 300
segment Premium

Part 6
# 6.1 Create a list of revenues after 10% tax.

In [2]:
revenues = [120, 250, 80, 310, 95]
new_revenues = []
for value in revenues:
    new_revenues.append(value *(1-0.05) )
new_revenues

[114.0, 237.5, 76.0, 294.5, 90.25]

# 6.2 Create a list of revenues greater than 100.

In [50]:
high_revenues = []
for value in revenues:
    if value > 100:
        high_revenues.append(value)

print (high_revenues)

[120, 250, 310]

# 6.3 Create a list labeling each revenue as:
“High” if > 200
“Normal” otherwise

In [51]:
labels = ["High" if  value > 200 else "Normal" for value in revenues]
labels

['Normal', 'High', 'Normal', 'High', 'Normal']

Part 7
# 7.1 Add column "revenue_after_tax".

In [3]:
import pandas as pd

data = {
    "revenue": revenues
}

df = pd.DataFrame(data)
df

   revenue
0      120
1      250
2       80
3      310
4       95

In [56]:
t=0.3
df["revenue_after_tax"] = df["revenue"] * (1-t)
df

   revenue  revenue_after_tax
0      120               84.0
1      250              175.0
2       80               56.0
3      310              217.0
4       95               66.5

# 7.2 Add column "segment" using conditional logic.

In [4]:
df.loc[df["revenue"] < 150, "segment" ] = "low"
df.loc[df["revenue"] >= 150, "segment" ] = "high"
df

   revenue segment
0      120     low
1      250    high
2       80     low
3      310    high
4       95     low

# 7.3 Filter rows where revenue > 100.

In [63]:
df[df["revenue"]> 100]

   revenue  revenue_after_tax segment
0      120               84.0     low
1      250              175.0    high
3      310              217.0    high

# 7.4 Remove the "revenue_after_tax" column.

In [ ]:
df = df.drop("revenue_after_tax", axis = 1)
df

# 7.5 Print the shape of the DataFrame.

In [10]:
df.info()
df.shape
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   revenue  5 non-null      int64
 1   segment  5 non-null      str
dtypes: int64(1), str(1)
memory usage: 212.0 bytes

Index(['revenue', 'segment'], dtype='str')