## Installing Packages

In [27]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

## Importing Data

In [28]:
# Reading data
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [29]:
df_orders.tail()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
3421078,2266710,206209,prior,10,5,18,29.00
3421079,1854736,206209,prior,11,4,10,30.00
3421080,626363,206209,prior,12,1,12,18.00
3421081,2977660,206209,prior,13,1,12,7.00
3421082,272231,206209,train,14,6,14,30.00

In [30]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [31]:
df_products = pd.read_csv('../data/raw/products.csv')
print(df_products.columns)
print(df_products.shape)
df_products.head()

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'prices'], dtype='str')
(49693, 5)

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [32]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department_id', 'department'], dtype='str')
(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [33]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

## Working with `Orders`

In [34]:

df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [35]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [36]:
df_orders['order_id'].nunique()

3421083

In [37]:
df_orders.shape

(3421083, 7)

In [38]:
## Consistancy Check: Order ID
if df_orders['order_id'].nunique() == df_orders.shape[0]:
    print('Happy')
else:
    print('Sad')

Happy

In [39]:
## 
df_orders['order_id'].nunique() == df_orders.shape[0]

True

In [40]:
df_orders['user_id'].nunique()

206209

In [41]:
df_orders['order_id'].nunique()/df_orders['user_id'].nunique()

16.590367054784224

In [42]:
df_orders['eval_set'].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [43]:
df_dow = df_orders['order_dow'].value_counts(ascending=False).reset_index().sort_values('order_dow')

In [44]:
df_dow.to_csv('../data/processed/dow.csv', index=False)

In [45]:
df_ohod = df_orders['order_hour_of_day'].value_counts().reset_index().sort_values('order_hour_of_day')
df_ohod.head()

    order_hour_of_day  count
18                  0  22758
19                  1  12398
21                  2   7539
23                  3   5474
22                  4   5527

In [46]:
df_ohod.to_csv('../data/processed/ohod.csv')

In [47]:
df_ohod.to_excel('../data/processed/ohod.xlsx',index=False)

ModuleNotFoundError: No module named 'openpyxl'

In [ ]:
df_orders["order_number"] == 1

0           True
1          False
2          False
3          False
4          False
           ...
3421078    False
3421079    False
3421080    False
3421081    False
3421082    False
Name: order_number, Length: 3421083, dtype: bool

In [ ]:
df_orders.loc[df_orders["order_number"] == 1, "days_since_prior_order"].isna().all()

np.True_

In [ ]:
needed_columns = ['days_since_prior_order','order_number','user_id']

In [ ]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [ ]:
df_first_orders = df_orders[['days_since_prior_order','order_number','user_id']]

In [ ]:
df_first_orders.head()

   days_since_prior_order  order_number  user_id
0                     NaN             1        1
1                   15.00             2        1
2                   21.00             3        1
3                   29.00             4        1
4                   28.00             5        1

In [ ]:
df_orders["order_id"].nunique()

3421083

In [ ]:
df_orders["order_dow"].between(0, 6).all()

np.True_

In [ ]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [ ]:
df_orders_train.shape

(131209, 7)

In [ ]:
df_orders_products_train["reordered"].value_counts(normalize=False)

reordered
1    828824
0    555793
Name: count, dtype: int64

In [ ]:
df_orders_products_train["reordered"].value_counts(normalize=True)

reordered
1   0.60
0   0.40
Name: proportion, dtype: float64

In [ ]:
df_orders_products_train["add_to_cart_order"].describe()

count   1,384,617.00
mean            8.76
std             7.42
min             1.00
25%             3.00
50%             7.00
75%            12.00
max            80.00
Name: add_to_cart_order, dtype: float64

In [ ]:
atr = 8/10

0.8

In [ ]:
df_orders_products_train["order_id"].is_unique

False

In [ ]:
df_orders_products_train.head(10)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1
5         1       13176                  6          0
6         1       47209                  7          0
7         1       22035                  8          1
8        36       39612                  1          0
9        36       19660                  2          1

In [ ]:
df_orders_products_train["order_id"].is_unique

False

In [ ]:
# add to cart order is one
df_orders_first_atc = df_orders_products_train[df_orders_products_train["add_to_cart_order"]==1]
df_orders_first_atc.shape

(131209, 4)

In [ ]:
df_orders_first_atc.head()

    order_id  product_id  add_to_cart_order  reordered
0          1       49302                  1          1
8         36       39612                  1          0
16        38       11913                  1          0
25        96       20574                  1          1
32        98        8859                  1          1

In [ ]:
# 24852 
df_orders_first_atc['product_id'].value_counts()

product_id
24852    4605
13176    3889
27845    1144
47766     995
21137     900
         ...
7044        1
28344       1
40866       1
13539       1
40800       1
Name: count, Length: 17908, dtype: int64

In [ ]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [ ]:
df_products.shape

(49693, 5)

In [ ]:
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 49693 entries, 0 to 49692
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49693 non-null  int64
 1   product_name   49677 non-null  str
 2   aisle_id       49693 non-null  int64
 3   department_id  49693 non-null  int64
 4   prices         49693 non-null  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 3.4 MB

In [ ]:
df_products.describe()

       product_id  aisle_id  department_id    prices
count   49,693.00 49,693.00      49,693.00 49,693.00
mean    24,844.35     67.77          11.73      9.99
std     14,343.72     38.32           5.85    453.52
min          1.00      1.00           1.00      1.00
25%     12,423.00     35.00           7.00      4.10
50%     24,845.00     69.00          13.00      7.10
75%     37,265.00    100.00          17.00     11.20
max     49,688.00    134.00          21.00 99,999.00

In [ ]:
df_products[df_products['product_name'].isna()==True]

       product_id product_name  aisle_id  department_id  prices
33             34          NaN       121             14   12.20
68             69          NaN        26              7   11.80
115           116          NaN        93              3   10.80
261           262          NaN       110             13   12.10
525           525          NaN       109             11    1.20
1511         1511          NaN        84             16   14.30
1780         1780          NaN       126             11   12.30
2240         2240          NaN        52              1   14.20
2586         2586          NaN       104             13   12.40
3159         3159          NaN       126             11   13.10
3230         3230          NaN       120             16   14.40
3736         3736          NaN        41              8   14.80
4283         4283          NaN        77              7   14.40
4790         4790          NaN        91             16   14.50
38187       38183          NaN        39             12   20.90
40444       40440          NaN       120             16   14.80

In [ ]:
49688-49693

-5

In [ ]:
# 13176
df_products[df_products['product_id']==24852]

       product_id product_name  aisle_id  department_id  prices
24853       24852       Banana        24              4   12.30

In [ ]:
df_products.sort_values(by='prices', ascending = False).head(1)

       product_id           product_name  aisle_id  department_id    prices
33666       33664  2 % Reduced Fat  Milk        84             16 99,999.00

In [ ]:
df_products["product_id"].nunique()

49686

In [ ]:
df_products.shape

(49693, 5)

In [ ]:
df_departments.head()
df_departments.shape

(21, 2)

In [ ]:
df_departments

    department_id       department
0               1           frozen
1               2            other
2               3           bakery
3               4          produce
4               5          alcohol
5               6    international
6               7        beverages
7               8             pets
8               9  dry goods pasta
9              10             bulk
10             11    personal care
11             12     meat seafood
12             13           pantry
13             14        breakfast
14             15     canned goods
15             16       dairy eggs
16             17        household
17             18           babies
18             19           snacks
19             20             deli
20             21          missing

In [ ]:
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [ ]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [ ]:
df_products_aisles =  pd.merge(df_products, df_aisles, on= "aisle_id", how = "left")

In [ ]:
df_products_aisles.head()

,product_id,product_name,aisle_id,department_id,prices,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes
1,2,All-Seasons Salt,104,13,9.30,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation

In [ ]:
df_products_aisles.head()

,product_id,product_name,aisle_id,department_id,prices,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes
1,2,All-Seasons Salt,104,13,9.30,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation

In [ ]:
df_products_aisles_department = pd.merge(df_products_aisles,df_departments, 
                                         on = 'department_id',
                                         how = 'left'
                                         
                                        )

In [ ]:
df_products_aisles_department.head()

,product_id,product_name,aisle_id,department_id,prices,aisle,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes,snacks
1,2,All-Seasons Salt,104,13,9.30,spices seasonings,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation,pantry

In [ ]:
df_products_aisles_department.drop(columns = ['aisle_id', 'department_id'], inplace = True)

In [ ]:
del df_departments
del df_products
del df_aisles

In [ ]:
df_products_aisles_department.head()

,product_id,product_name,prices,aisle,department
0,1,Chocolate Sandwich Cookies,5.80,cookies cakes,snacks
1,2,All-Seasons Salt,9.30,spices seasonings,pantry
2,3,Robust Golden Unsweetened Oolong Tea,4.50,tea,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,10.50,frozen meals,frozen
4,5,Green Chile Anytime Sauce,4.30,marinades meat preparation,pantry

In [ ]:
df_products_aisles_department['department'].value_counts()

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1116
babies             1081
alcohol            1056
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [ ]:
pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="outer",
    indicator = True
).head()

,product_id,product_name,aisle_id,department_id,prices,department,_merge
0,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen,both
1,8,Cut Russet Potatoes Steam N' Mash,116,1,1.10,frozen,both
2,12,Chocolate Fudge Layer Cake,119,1,9.40,frozen,both
3,18,Pizza for One Suprema Frozen Pizza,79,1,10.60,frozen,both
4,30,"Three Cheese Ziti, Marinara with Meatballs",38,1,13.80,frozen,both

In [ ]:
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left"
)

df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks
1,2,All-Seasons Salt,104,13,9.30,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry

In [49]:
df_products_enriched = pd.merge(
    df_products_departments,
    df_aisles,
    on="aisle_id",
    how="left"
)

df_products_enriched.head()

,product_id,product_name,aisle_id,department_id,prices,department,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks,cookies cakes
1,2,All-Seasons Salt,104,13,9.30,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry,marinades meat preparation

In [ ]:
df_products_aisles_check= pd.merge(
    df_products_departments,
    df_aisles,
    on="aisle_id",
    how="left",
    indicator= True
)

df_products_aisles_check['_merge'].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64

In [ ]:
df_products_aisles_check [df_products_aisles_check['_merge'] == "left_only"].head()

Empty DataFrame
Columns: [product_id, product_name, aisle_id, department_id, prices, department, aisle, _merge]
Index: []

In [50]:
print(df_products.shape)
print(df_products_departments.shape)
print(df_products_enriched.shape)

(49693, 5)
(49693, 6)
(49693, 7)

In [51]:
df_departments["department_id"].is_unique

True

In [52]:
df_aisles["aisle_id"].is_unique

True

In [54]:
df_products_enriched["aisle"].value_counts().head(10)

aisle
missing                 1258
candy chocolate         1246
ice cream ice           1091
vitamins supplements    1038
yogurt                  1026
chips pretzels           989
tea                      894
packaged cheese          891
frozen meals             880
cookies cakes            874
Name: count, dtype: int64

In [55]:
pd.crosstab(
    df_products_enriched["department"],
    df_products_enriched["aisle"]
)

aisle,air fresheners candles,asian foods,baby accessories,baby bath body care,baby food formula,bakery desserts,baking ingredients,baking supplies decor,beauty,beers coolers,...,spreads,tea,tofu meat alternatives,tortillas flat bread,trail mix snack mix,trash bags liners,vitamins supplements,water seltzer sparkling water,white wines,yogurt
department,,,,,,,,,,,,,,,,,,,,,
alcohol,0,0,0,0,0,0,0,0,0,387,...,0,0,0,0,0,0,0,0,147,0
babies,0,0,44,132,718,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bakery,0,0,0,0,0,297,0,0,0,0,...,0,0,0,241,0,0,0,0,0,0
beverages,0,0,0,0,0,0,0,0,0,0,...,0,894,0,0,0,0,0,344,0,0
breakfast,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bulk,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
canned goods,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dairy eggs,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1026
deli,0,0,0,0,0,0,0,0,0,0,...,0,0,159,0,0,0,0,0,0,0
dry goods pasta,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
frozen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
household,355,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,112,0,0,0,0
international,0,605,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
meat seafood,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
missing,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
other,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pantry,0,0,0,0,0,0,623,290,0,0,...,493,0,0,0,0,0,0,0,0,0
personal care,0,0,0,0,0,0,0,0,178,0,...,0,0,0,0,0,0,1038,0,0,0
pets,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
produce,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
snacks,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,69,0,0,0,0,0

In [57]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [58]:
df_train_transactions = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left"
)

df_train_transactions.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,1187899,1,train,11,4,8,14.00,196,1,1
1,1187899,1,train,11,4,8,14.00,25133,2,1
2,1187899,1,train,11,4,8,14.00,38928,3,1
3,1187899,1,train,11,4,8,14.00,26405,4,1
4,1187899,1,train,11,4,8,14.00,39657,5,1

In [59]:
df_train_transactions_check = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left",
    indicator=True
)

df_train_transactions_check.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,1187899,1,train,11,4,8,14.00,196,1,1,both
1,1187899,1,train,11,4,8,14.00,25133,2,1,both
2,1187899,1,train,11,4,8,14.00,38928,3,1,both
3,1187899,1,train,11,4,8,14.00,26405,4,1,both
4,1187899,1,train,11,4,8,14.00,39657,5,1,both

In [60]:
df_train_transactions_check[
    df_train_transactions_check["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [order_id, user_id, eval_set, order_number, order_dow, order_hour_of_day, days_since_prior_order, product_id, add_to_cart_order, reordered, _merge]
Index: []

In [61]:
print(df_orders_train.shape)
print(df_orders_products_train.shape)
print(df_train_transactions.shape)

(131209, 7)
(1384617, 4)
(1384617, 10)

In [62]:
df_train_transactions.groupby("order_id").size().head()

order_id
1      8
36     8
38     9
96     7
98    49
dtype: int64

In [63]:
df_train_transactions.groupby("order_id").size().describe()

count   131,209.00
mean         10.55
std           7.93
min           1.00
25%           5.00
50%           9.00
75%          14.00
max          80.00
dtype: float64

In [64]:
df_train_transactions.groupby("order_dow").size() / df_train_transactions["order_id"].nunique()

order_dow
0   2.47
1   1.57
2   1.22
3   1.18
4   1.18
5   1.35
6   1.58
dtype: float64

In [65]:
basket_size_by_order = (
    df_train_transactions
    .groupby(["order_id", "order_dow"])
    .size()
    .reset_index(name="basket_size")
)

basket_size_by_order.groupby("order_dow")["basket_size"].mean()

order_dow
0   11.80
1   10.47
2    9.96
3    9.84
4    9.74
5   10.16
6   10.97
Name: basket_size, dtype: float64

In [66]:
df_train_transactions.groupby("order_hour_of_day")["reordered"].mean()

order_hour_of_day
0    0.57
1    0.58
2    0.58
3    0.58
4    0.60
5    0.62
6    0.65
7    0.65
8    0.64
9    0.62
10   0.61
11   0.59
12   0.59
13   0.59
14   0.59
15   0.58
16   0.59
17   0.59
18   0.58
19   0.59
20   0.60
21   0.61
22   0.60
23   0.59
Name: reordered, dtype: float64

In [67]:
df_train_transactions["product_id"].isna().sum()

np.int64(0)

In [68]:
df_train_transactions["user_id"].isna().sum()

np.int64(0)

In [69]:
df_train_transactions["order_id"].value_counts().head()

order_id
2813632    80
1395075    80
949182     77
2869702    76
341238     76
Name: count, dtype: int64

In [70]:
df_train_analytic = pd.merge(
    df_train_transactions,
    df_products_enriched,
    on="product_id",
    how="left"
)

df_train_analytic.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle
0,1187899,1,train,11,4,8,14.00,196,1,1,Soda,77.00,7.00,9.00,beverages,soft drinks
1,1187899,1,train,11,4,8,14.00,25133,2,1,Organic String Cheese,21.00,16.00,8.60,dairy eggs,packaged cheese
2,1187899,1,train,11,4,8,14.00,38928,3,1,0% Greek Strained Yogurt,120.00,16.00,12.60,dairy eggs,yogurt
3,1187899,1,train,11,4,8,14.00,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.00,17.00,1.00,household,paper goods
4,1187899,1,train,11,4,8,14.00,39657,5,1,Milk Chocolate Almonds,45.00,19.00,6.80,snacks,candy chocolate

In [71]:
df_train_analytic_check = pd.merge(
    df_train_transactions,
    df_products_enriched,
    on="product_id",
    how="left",
    indicator=True
)

df_train_analytic_check["_merge"].value_counts()

_merge
both          1384618
left_only          88
right_only          0
Name: count, dtype: int64

In [72]:
df_train_analytic_check[
    df_train_analytic_check["_merge"] == "left_only"
].head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle,_merge
10780,3009052,1629,train,37,0,13,3.00,6799,24,1,NaN,NaN,NaN,NaN,NaN,NaN,left_only
52822,195363,7955,train,12,6,14,8.00,6799,4,1,NaN,NaN,NaN,NaN,NaN,NaN,left_only
59749,831974,9000,train,11,3,13,20.00,6799,19,0,NaN,NaN,NaN,NaN,NaN,NaN,left_only
64159,206208,9640,train,16,6,11,12.00,6799,6,1,NaN,NaN,NaN,NaN,NaN,NaN,left_only
81585,472316,12168,train,10,4,12,0.00,6799,12,1,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [73]:
df_train_analytic["product_name"].value_counts().head(10)

product_name
Banana                    18726
Bag of Organic Bananas    15480
Organic Strawberries      10894
Organic Baby Spinach       9784
Large Lemon                8135
Organic Avocado            7409
Organic Hass Avocado       7293
Strawberries               6494
Limes                      6033
Organic Raspberries        5546
Name: count, dtype: int64

In [74]:
df_train_analytic["department"].value_counts()

department
produce            409087
dairy eggs         217051
snacks             118862
beverages          113962
frozen             100426
pantry              81242
bakery              48394
canned goods        46799
deli                44291
dry goods pasta     38713
household           35986
meat seafood        30307
breakfast           29552
personal care       21599
babies              14941
international       11902
missing              8251
alcohol              5602
pets                 4497
other                1795
bulk                 1359
Name: count, dtype: int64

In [75]:
df_train_analytic.groupby("department")["reordered"].mean().sort_values(ascending=False)

department
dairy eggs        0.67
produce           0.66
beverages         0.66
bakery            0.63
pets              0.63
deli              0.62
alcohol           0.61
meat seafood      0.59
snacks            0.58
bulk              0.58
breakfast         0.57
frozen            0.56
babies            0.54
dry goods pasta   0.49
canned goods      0.49
household         0.43
other             0.39
missing           0.38
international     0.38
pantry            0.36
personal care     0.34
Name: reordered, dtype: float64

In [76]:
pd.crosstab(
    df_train_analytic["department"],
    df_train_analytic["reordered"]
)

reordered             0       1
department
alcohol            2203    3399
babies             6857    8084
bakery            17702   30692
beverages         38960   75002
breakfast         12654   16898
bulk                573     786
canned goods      24017   22782
dairy eggs        70549  146502
deli              16924   27367
dry goods pasta   19828   18885
frozen            44258   56168
household         20614   15372
international      7380    4522
meat seafood      12400   17907
missing            5103    3148
other              1098     697
pantry            51744   29498
personal care     14309    7290
pets               1663    2834
produce          137201  271886
snacks            49760   69102

In [77]:
pd.crosstab(
    df_train_analytic["order_dow"],
    df_train_analytic["reordered"],
    normalize="index"
)

reordered    0    1
order_dow
0         0.39 0.61
1         0.40 0.60
2         0.41 0.59
3         0.41 0.59
4         0.41 0.59
5         0.39 0.61
6         0.41 0.59

In [ ]:
url = 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/customers.csv'

In [79]:

import pandas as pd

url = 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/'
l = ['customers','states']


for i in l:
    dfname = url + i +'.csv'
    df = pd.read_csv(dfname)
    df.to_csv(f'../data/raw/{i}.csv')
    print(dfname)

https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/customers.csv
https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/states.csv

In [ ]:
import pandas as pd
SQL_URL = "https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/"
TO_SAVE_URL = 'C:/Users/120/Desktop/aca/sql-analytics-portfolio/data/public_schema'
l = ['customers', 'employees','orders','products', 'sales']

for i in l:
    print(100*'-')
    print(f"trying to download {i}.csv")
    df = pd.read_csv(SQL_URL+i+'.csv')
    print(f"{i}.csv is downloaded")
    print(f"the shape of {i}.csv : {df.shape}")
    print(f"trying to save  {i}.csv")
    df.to_csv(TO_SAVE_URL+i+'.csv',index=False)
    print(f"{i}.csv is successfully saved")

----------------------------------------------------------------------------------------------------
trying to download customers.csv
customers.csv is downloaded
the shape of customers.csv : (2000, 5)
trying to save  customers.csv
customers.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download employees.csv
employees.csv is downloaded
the shape of employees.csv : (100, 5)
trying to save  employees.csv
employees.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download orders.csv
orders.csv is downloaded
the shape of orders.csv : (200, 5)
trying to save  orders.csv
orders.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download products.csv
products.csv is downloaded
the shape of products.csv : (100, 5)
trying to save  products.csv
products.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download sales.csv
sales.csv is downloaded
the shape of sales.csv : (5000, 8)
trying to save  sales.csv
sales.csv is successfully saved

In [81]:
df_customers = pd.read_csv('../data/raw/customers.csv')
df_states = pd.read_csv('../data/raw/states.csv')

In [82]:
df_customers.head()

,Unnamed: 0,user_id,First Name,Surname,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [83]:
df_states.head()

   Unnamed: 0          state     region     division
0           0    Connecticut  Northeast  New England
1           1          Maine  Northeast  New England
2           2  Massachusetts  Northeast  New England
3           3  New Hampshire  Northeast  New England
4           4   Rhode Island  Northeast  New England

In [84]:
df_customers.rename(columns={'STATE':'state'}, inplace=True)

In [85]:
df_customers_states = df_customers.merge(df_states,on = 'state')

In [86]:
df_customers_states.head()

,Unnamed: 0_x,user_id,First Name,Surname,Gender,state,Age,date_joined,n_dependants,fam_status,income,Unnamed: 0_y,region,division
0,0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665,17,Midwest,West North Central
1,1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285,43,West,Mountain
2,2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568,40,West,Mountain
3,3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049,14,Midwest,West North Central
4,4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374,25,South,South Atlantic

In [87]:
df_train_analytics_final = df_train_analytic.merge(df_customers_states, on='user_id', how='left')

In [88]:
df_train_analytics_final.drop(columns=['user_id','eval_set','product_id', 'aisle_id', 'department_id'],inplace=True)

In [89]:
print(df_train_analytics_final.shape)
df_train_analytics_final.head()

(1384706, 24)

,order_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,product_name,prices,department,...,Gender,state,Age,date_joined,n_dependants,fam_status,income,Unnamed: 0_y,region,division
0,1187899,11,4,8,14.00,1,1,Soda,9.00,beverages,...,Female,Alabama,31,2/17/2019,3,married,40423,30,South,East South Central
1,1187899,11,4,8,14.00,2,1,Organic String Cheese,8.60,dairy eggs,...,Female,Alabama,31,2/17/2019,3,married,40423,30,South,East South Central
2,1187899,11,4,8,14.00,3,1,0% Greek Strained Yogurt,12.60,dairy eggs,...,Female,Alabama,31,2/17/2019,3,married,40423,30,South,East South Central
3,1187899,11,4,8,14.00,4,1,XL Pick-A-Size Paper Towel Rolls,1.00,household,...,Female,Alabama,31,2/17/2019,3,married,40423,30,South,East South Central
4,1187899,11,4,8,14.00,5,1,Milk Chocolate Almonds,6.80,snacks,...,Female,Alabama,31,2/17/2019,3,married,40423,30,South,East South Central

In [96]:
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw")

In [98]:
import zipfile
with zipfile.ZipFile("../data/raw/order_products_prior.parquet.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw")

In [99]:
df_parquet = pd.read_parquet("../data/raw/order_products_prior.parquet")

In [100]:
df_train_analytics_final.to_parquet("../data/processed/instacart.parquet", index = False)

In [101]:
df_train_analytics_final.to_csv("../data/processed/instacart.csv", index = False)